/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.messaging;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMESSAGING_SYNCHINPROGRESS;
    public static final int ATTRIBUTE_ID_DSIMESSAGING_MESSAGINGACCOUNTS;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SMSCNUMBER;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SMSDELIVERYREPORT;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_STORESMSONSENT;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SHORTMESSAGEVALIDITYPERIOD;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_PHONESYSTEMRINGINGVOLUME;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_PHONESYSTEMRINGINGTYPE;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_EMAILINCLUDEOLDMAILINREPLY;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_EMAILEMPTYSUBJECTNOTIFICATION;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_FOLDERVIEWMODE;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_ACCOUNTPREFERENCES;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SMSINDICATIONS;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_EMAILINDICATIONS;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_PUSHSMS;
}

