/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.media;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_PARENTALML;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_PREFERREDLANGUAGE;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_MEDIALIST;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_DEVICELIST;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_CUSTOMERUPDATE;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_APPLICATIONVERSION;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_METADATADBVERSION;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_PROFILESTATE;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_BROWSEMODE;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_CONTENTFILTER;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_BROWSEMEDIA;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_BROWSEFOLDER;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_LISTSIZE;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_SEARCHSPELLERSTATE;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_SEARCHSIZE;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_ALPHABETICALINDEX;
    public static final int ATTRIBUTE_ID_DSIMEDIAONLINE_BUFFERSTATE;
    public static final int ATTRIBUTE_ID_DSIMEDIAONLINE_BUFFERFILLINFO;
    public static final int ATTRIBUTE_ID_DSIMEDIAONLINE_AUDIOSETTINGS;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_VIDEOFORMAT;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_VIDEONORM;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_CMDBLOCKINGMASK;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_NUMVIDEOANGLES;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKMODELIST;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKMODE;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKSTATE;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVEMEDIA;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKFOLDER;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_CAPABILITIES;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYPOSITION;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYVIEWSIZE;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVEVIDEOANGLE;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_AUDIOSTREAMLIST;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVEAUDIOSTREAM;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_SUBTITLELIST;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVESUBTITLE;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKCONTENTFOLDER;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_ACTIVEMEDIA;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_IMPORTSUMMARY;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_IMPORTPROGRESS;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_DELETIONPROGRESS;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_DATABASESPACE;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_IMPORTSTATUS;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_DELETIONSTATUS;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_TARGETMEDIA;
    public static final int ATTRIBUTE_ID_DSIMEDIAROUTER_STREAMINGSTATUS;
    public static final int ATTRIBUTE_ID_DSIMEDIAROUTER_ACTIVEAUDIOROUTES;
    public static final int ATTRIBUTE_ID_DSIMETADATASERVICE_ONLINELOOKUPSTATUS;
    public static final int ATTRIBUTE_ID_DSIRADIOTAGGING_COMPATIBLEDEVAVAIL;
}

