/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carhybrid;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDCHARGE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYFLOWSTATE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDRECOVEREDENERGY;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYFLOW;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPLUG;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLCHARGESTATE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLCLIMATESTATE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMERSTATE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER1;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER2;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER3;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER4;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTOTALNUMBEROFPROFILES;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPROFILESLISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTOTALNUMBEROFPOWERPROVIDER;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPOWERPROVIDERLISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDTARGETRANGE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYASSISTCONTROL;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYASSISTSTATE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPASTERRORREASON;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPLUGDISPLAYSTATE;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLREMAININGCHARGETIME;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLLOWESTMAXCURRENT;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDINHIBITREASON;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDACTIVEPEDAL;
}

