/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carseat;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATRADIOKEYAUTOMATIC;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSPECIALPOSITION;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFRONTLEFTSTOPBUTTON;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFRONTRIGHTSTOPBUTTON;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCODRIVERSETTINGSFROMDRIVER;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCODRIVERSETTINGSFROMREAR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCONTENT;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYFRONTLEFT;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYFRONTRIGHT;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYREARLEFT;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYREARRIGHT;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICCODRIVERSETTINGSFROMDRIVER;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICMASSAGEDATA1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICMASSAGEDATA1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAUP1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATADOWN1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAFORWARD1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATABACK1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAUP1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATADOWN1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAFORWARD1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATABACK1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICCONTENT;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATREARLEFTSTOPBUTTON;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATREARRIGHTSTOPBUTTON;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSPECIALPOSITIONREARCODRIVER;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCODRIVERSETTINGSFROMREARACTIVATION;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATRESTSEATSTATUS;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFOLDHEADRESTREARDRIVER;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFOLDHEADRESTREARCODRIVER;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER2RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER1RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER1RR;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER2RL;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER2RR;
}

