/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.organizer;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWENTRYAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWPUBLICPROFILEENTRYAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWTOPDESTINATIONENTRYAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWPUBLICPROFILETOPDESTENTRYAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWONLINEDESTINATIONENTRYAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIADBINIT_DEFAULTPUBLICPROFILEVISIBILITY;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXLOCALENTRIES;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXPHONEENTRIES;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXTOPDESTENTRIES;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXSPEEDDIALENTRIES;
    public static final int ATTRIBUTE_ID_DSIADBINIT_AUTOPROFILEALLOCATION;
    public static final int ATTRIBUTE_ID_DSIADBINIT_DEFAULTSOSBUTTON;
    public static final int ATTRIBUTE_ID_DSIADBLIST_VIEWSIZE;
    public static final int ATTRIBUTE_ID_DSIADBLIST_ALPHABETICALINDEX;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_ADBSTATE;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_SORTORDER;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_PICTUREVISIBILITY;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_CONTEXTSPECIFICVISIBILITY;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_PROFILEINFO;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DEVICECONNECTED;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADCOUNTSIM;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADCOUNTME;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADCOUNTOPP;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADSTATE;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADSTATE2NDPHONE;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_SOSBUTTON;
    public static final int ATTRIBUTE_ID_DSIADBVCARDEXCHANGE_EXPORTCOUNT;
    public static final int ATTRIBUTE_ID_DSIADBVCARDEXCHANGE_IMPORTCOUNT;
}

