/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carauxheatercooler;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERSTATE;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERONOFF;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERREMAININGTIME;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERRUNNINGTIME;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERMODE;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERENGINEHEATER;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERACTIVETIMER;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTIMER1;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTIMER2;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTIMER3;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERDEFAULTSTARTMODE;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERERRORREASON;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERCURRENTHEATERSTATE;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERPOPUP;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERMODE2;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLEREXTENDEDCONDITIONING;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERWINDOWHEATING;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERUNLOCKCLIMATING;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTARGETTEMPERATURE;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERAIRQUALITY;
}

