/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.telephoneng;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_DTMFTONEPLAYING;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_EMERGENCYNUMBERS;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SIMPINREQUIRED;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ACTIVATIONSTATE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_AUTOMATICPINENTRYACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_AUTOMATICREDIALACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_BATTERYCHARGELEVEL;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CALLDURATIONLIST;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CALLLIST;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CDMATHREEWAYCALLINGSETTING;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CRADLEPLUGINSTATE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_DISCONNECTREASON;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_EMERGENCYCALLACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ENHANCEDPRIVACYMODE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_HANDSFREEMODE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_LOCKSTATE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MAILBOXCONTENT;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MICMUTESTATE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NADTEMPERATURE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PHONEINFORMATION;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NETWORKPROVIDER;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NETWORKTYPE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PRIVACYMODE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_REGISTERSTATE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SERVICECODETYPE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SERVICENUMBERS;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SIGNALQUALITY;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SUPPSERVICERESPONSE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SERVICEPROVIDER;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SIMALIASINFORMATION;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MICGAINLEVEL;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_OPTIMIZATIONMODE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NADMODE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_OTHERSIMAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PREFIXCONTENT;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PHONEREMINDERSETTING;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PREFIXACTIVATED;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_WIDEBANDSPEECH;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PHONERINGTONE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_FAVORITES;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SAPUPGRADEACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_EUICCID;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ESIMMSISDN;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ESIMACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ESIMB2BMODE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CALLSTACKSISREVERTED;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_LASTANSWEREDNUMBERS;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_LASTDIALEDNUMBERS;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MISSEDNUMBERS;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MEDATAVALIDITY;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MISSEDCALLINDICATOR;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SPEECHRECOGNITIONAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SPEECHRECOGNITIONACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SPEECHRECOGNITIONTYPE;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENTTOPOLOGY_TOPOLOGY;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENTTOPOLOGY_USAGE;
}

