/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.mirrorlink;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DISCOVEREDDEVICES;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DEVICECONNECTIONSTATUS;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DEVICESOFTKEYS;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_APPLICATIONSTATUS;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SCREENORIENTATION;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SHOWKEYBOARD;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SCREENORIENTATIONAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SCREENROTATIONAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_AUDIOCONNECTIONREQUESTED;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_AVAILABLEAPPLICATIONSLIST;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SINGLEAPPLICATIONMODE;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_PHONEVIEWAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_UNCERTIFIEDCONTENT;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DEVICESTATUS;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SWAPSTATUS;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SHOWNOTIFICATION;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_NOTIFICATIONSERVICEENABLED;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_LOCATIONDATASERVICESENABLED;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SWITCHTOCLIENTNATIVEUI;
}

