/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.careco;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARECO_BCMEVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMELISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMPTION;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMELIVETIP;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTCONSUMPTIONUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMEENERGYFLOWCOMFORT;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMERANGEGAINTOTAL;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTRANGEUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECURRENTRANGE;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTTOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTCONSUMPTIONTOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTRANGETOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPPROHIBITREASONLISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTREASONLISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTPROHIBITREASONLISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPSTATE;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPPROHIBITREASONLISTTOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTREASONLISTTOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTPROHIBITREASONLISTTOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPCOLLECTEDREASONS;
    public static final int ATTRIBUTE_ID_DSICARECO_RDVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONMOTORWAY1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONMOTORWAY2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONHIGHWAY1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONHIGHWAY2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONCOUNTRYROAD1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONCOUNTRYROAD2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONDISTRICTROAD1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONDISTRICTROAD2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONLOCALROAD1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONLOCALROAD2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONRURALROAD1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONRURALROAD2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONUNCLASSIFIEDROAD1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONUNCLASSIFIEDROAD2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDMAXRANGE1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDMAXRANGE2;
    public static final int ATTRIBUTE_ID_DSICARECO_RDRESIDUALENERGY1;
    public static final int ATTRIBUTE_ID_DSICARECO_RDRESIDUALENERGY2;
    public static final int ATTRIBUTE_ID_DSICARECO_EAVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARECO_EASYSTEM;
    public static final int ATTRIBUTE_ID_DSICARECO_EAPEDALJERK;
    public static final int ATTRIBUTE_ID_DSICARECO_EAFREEWHEELING;
    public static final int ATTRIBUTE_ID_DSICARECO_EASTARTSTOP;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECURRENTRANGESOC;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECATALOGUERANGE;
}

