/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.telephone;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_ISREVERTED;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_LASTANSWEREDNUMBERS;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_LASTDIALEDNUMBERS;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_MISSEDNUMBERS;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_MEDATAVALIDITY;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_MISSEDCALLINDICATOR;
    public static final int ATTRIBUTE_ID_DSIMOBILESPEECHRECOGNITION_SPEECHRECOGNITIONAVAILABLE;
    public static final int ATTRIBUTE_ID_DSIMOBILESPEECHRECOGNITION_SPEECHRECOGNITIONACTIVE;
    public static final int ATTRIBUTE_ID_DSIMOBILESPEECHRECOGNITION_SPEECHRECOGNITIONTYPE;
    public static final int ATTRIBUTE_ID_DSINAD_SIMPINREQUIRED;
    public static final int ATTRIBUTE_ID_DSINAD_ACTIVATIONSTATE;
    public static final int ATTRIBUTE_ID_DSINAD_AUTOMATICPINENTRYACTIVE;
    public static final int ATTRIBUTE_ID_DSINAD_LOCKSTATE;
    public static final int ATTRIBUTE_ID_DSINAD_NADTEMPERATURE;
    public static final int ATTRIBUTE_ID_DSINAD_PHONEINFORMATION;
    public static final int ATTRIBUTE_ID_DSINAD_NETWORKPROVIDER;
    public static final int ATTRIBUTE_ID_DSINAD_NETWORKTYPE;
    public static final int ATTRIBUTE_ID_DSINAD_REGISTERSTATE;
    public static final int ATTRIBUTE_ID_DSINAD_SIGNALQUALITY;
    public static final int ATTRIBUTE_ID_DSINAD_SERVICEPROVIDER;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_DTMFTONEPLAYING;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_EMERGENCYNUMBERS;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SIMPINREQUIRED;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ACTIVATIONSTATE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_AUTOMATICPINENTRYACTIVE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_AUTOMATICREDIALACTIVE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_BATTERYCHARGELEVEL;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CALLDURATIONLIST;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CALLLIST;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CDMATHREEWAYCALLINGSETTING;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CRADLEPLUGINSTATE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_DISCONNECTREASON;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_EMERGENCYCALLACTIVE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ENHANCEDPRIVACYMODE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_HANDSFREEMODE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_LOCKSTATE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_MAILBOXCONTENT;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_MICMUTESTATE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NADTEMPERATURE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PHONEINFORMATION;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NETWORKPROVIDER;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NETWORKTYPE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PRIVACYMODE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_REGISTERSTATE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SERVICECODETYPE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SERVICENUMBERS;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SIGNALQUALITY;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SUPPSERVICERESPONSE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SERVICEPROVIDER;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SIMALIASINFORMATION;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_MICGAINLEVEL;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_OPTIMIZATIONMODE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NADMODE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_OTHERSIMAVAILABLE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ALTERNATEPHONEACTIVITY;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PREFIXCONTENT;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PHONEREMINDERSETTING;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ACTIVATIONSTATEASSOCIATED;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PREFIXACTIVATED;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_WIDEBANDSPEECH;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PHONERINGTONE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_FAVORITES;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SAPUPGRADEACTIVE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_EUICCID;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ESIMMSISDN;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ESIMACTIVE;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ESIMB2BMODE;
}

