/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.cardrivingcharacteristics;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLLIFTMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLCARJACKMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLTRAILERMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLLOADINGMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACTIVEPROFILE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACCESSIBLEAIRPROFILES;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACCESSIBLEDRCPROFILES;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLVEHICLESTATUS;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACTIVEMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCEASYENTRY;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCPITCHCONTROL;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCSPECIALPOSITION;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCPREVIEW;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCPREVIEWSTATE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACTUATORINFO;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAACTIVEPROFILE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMALISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMACONTENT;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMATRAILERDETECTION;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMATRAILERSETTING;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAPROGBUTTON;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMASOUND;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADCONTENT;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADVEHICLEINFO;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADCURRENTROLLANGLE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADCURRENTPITCHANGLE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADPOSMAXROLLANGLE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADNEGMAXROLLANGLE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADPOSMAXPITCHANGLE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADNEGMAXPITCHANGLE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAACTIVEOPERATIONMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLCURRENTLEVEL;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLTARGETLEVEL;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLHEIGHTINFO;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLOPERATIONMESSAGES;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERPOSITIONSELECTION;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERSTATE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERACTUATION;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERMESSAGES;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERSYSTEMONOFF;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLSNOWCHAINMODE;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLVEHICLESTATECONTROL;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDSYSTEMONOFF;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDONOFF;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDSTYLE;
}

