/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carlight;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTCOLOUR;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTSTATE;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTENVIRONMENT;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTSPEED;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTTEMPERATURE;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTBRIGHTNESS;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET1;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET2;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET3;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET4;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET5;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET6;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET7;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET8;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE1;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE2;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE3;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE4;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE5;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE6;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE7;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE8;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTACTIVEPROFILE;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTAMBIENTLIGHTCOLOR;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTCONTOURLIGHTCOLOR;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTFOLLOWUPTIME;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTRGBCOLORLISTUPDATEINFO;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTRGBCOLORLISTTOTALNUMBEROFELEMENTS;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTDOORCONTACT;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTCOMINGHOME;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLEAVINGHOME;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTSWITCHONSENSITIVITY;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTDAYLIGHT;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTTOURIST;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTADAPTIVE;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTHEADLIGHTSYSTEM;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTGLIDINGSYSTEM;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTMOTORWAYBLINKING;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTMASKEDHIGHBEAM;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLAMPERRORDETECTION;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLAMPERRORDETECTIONTRAILER;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTSENSORERRORDETECTION;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLASERLIGHT;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTAUTOMATICLIGHT;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTSIGNATURELIGHT;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTHEADLIGHTRANGE;
}

