/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.online;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIDESTINATIONIMPORT_ENTRIES;
    public static final int ATTRIBUTE_ID_DSIONLINEESIMTRAFFICNOTIFICATION_ESIMNOTIFICATION;
    public static final int ATTRIBUTE_ID_DSIONLINEPICNAV_SYNCSTATUS;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_APPLICATIONSTATE;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_DEVICEENUMERATOR;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_EXTERNALPROFILEINFO;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_COREPROFILEINFO;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICESTATE;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICELIST;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_PROFILESTATE;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICES;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICEREGISTRATION;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SPINREQUIRED;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFIC_CONSUMERREADY;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFIC_WANTONLINETRAFFICDATA;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFICLIGHTINFO_TRAFFICLIGHTINFO;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFICLIGHTINFO_TRAFFICLIGHTSPEED;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFICLIGHTINFO_TRAFFICLIGHTTIME;
}

