/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.networking;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_AVAILABLEPROFILES;
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_ACTIVEPROFILE;
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_ROAMINGSTATE;
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_CONNECTIONMODE;
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_DATAREQUEST;
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_REQUESTSETTING;
    public static final int ATTRIBUTE_ID_DSIDATACONFIGURATION_PACKETCOUNTER;
    public static final int ATTRIBUTE_ID_DSIDATACONNECTION_STATEDATACONNECTION;
    public static final int ATTRIBUTE_ID_DSIDATACONNECTION_ERRORSTATE;
    public static final int ATTRIBUTE_ID_DSIDATACONNECTION_CONNECTIONSTATEINFORMATION;
    public static final int ATTRIBUTE_ID_DSIDATACONNECTION_ROAMINGSTATE;
    public static final int ATTRIBUTE_ID_DSIWLAN_ROLE;
    public static final int ATTRIBUTE_ID_DSIWLAN_RFACTIVE;
    public static final int ATTRIBUTE_ID_DSIWLAN_NODELIST;
    public static final int ATTRIBUTE_ID_DSIWLAN_WLANENABLED;
    public static final int ATTRIBUTE_ID_DSIWLAN_STARTUPSTATE;
    public static final int ATTRIBUTE_ID_DSIWLAN_DISCOVEREDNETWORK;
    public static final int ATTRIBUTE_ID_DSIWLAN_CONNECTEDNETWORK;
    public static final int ATTRIBUTE_ID_DSIWLAN_TRUSTEDNETWORKS;
    public static final int ATTRIBUTE_ID_DSIWLAN_PROFILE;
    public static final int ATTRIBUTE_ID_DSIWLAN_WPSRUNNING;
    public static final int ATTRIBUTE_ID_DSIWLAN_WPSSTOPPEDANDCONNECTING;
}

