/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.powermanagement;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_POWERMANAGEMENTSTATE;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_POWERMANAGEMENTSTATERIGHT;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_BEMSTATE;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_CLAMPSIGNAL;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_CHILDLOCKSTATE;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_LASTON;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_RVCACTIVE;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_TELMAXPOPUP;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_SPLASHSCREENANIMATION;
    public static final int ATTRIBUTE_ID_DSIPOWERMANAGEMENT_TSTANDBYPOPUP;
}

