/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.kombisync2;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBICOMMUNICATIONSTATE;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEDISPLAYIDENTIFICATION;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEDISPLAYREQUESTRESPONSE;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEDISPLAYSTATUS;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEPOPUPACTIONREQUEST;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEPOPUPREGISTERRESPONSE;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEPOPUPSTATUS;
}

