/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.speechrec;

public class Consts {
    public static final int ATTRIBUTE_ID_DSISPEECHREC_LANGUAGE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_AVAILABLELANGUAGES;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ABORTED;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_FAILURE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_RECOGNIZERSTATE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ABSOLUTECONFIDENCETHRESHOLD;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_MAXCOMMANDNBESTLISTSIZE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_MAXSLOTNBESTLISTSIZE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_CONFIDENCEREJECTTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_UTTERANCESTARTTIMEOUT;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_RECOGNITIONTIMEOUT;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_UNAMBIGUOUSRESULTTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_UNAMBIGUOUSRESULTRANGE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_FIRSTLEVELSIZE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_SDSAVAILABILITY;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_TEMPORARYG2PLANGUAGECHANGEACTIVE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_AVAILABLEPROFILES;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_GRAMMARSTATUS;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_GRAMMARSTATE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_NBESTLIST;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ASRPARAMETERCONFIGURATION;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_VDEMEDIUMSTATE;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_AVAILABLESLMLANGUAGES;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ONLINECAPABILITIES;
}

