/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carvehiclestates;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_OILLEVELVIEWOPTION;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_OILLEVELDATA;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_VINVIEWOPTION;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_VINDATA;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_KEYVIEWOPTION;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_KEYDATA;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DRVSCHOOLSYSTEM;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_VEHICLEINFOVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOHIGHFREQUENTVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOMIDFREQUENTVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOHIGHFREQUENT;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOMIDFREQUENT;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_SEMISTATICVEHICLEDATAVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_SEMISTATICVEHICLEDATA;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOSCR;
}

