/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.generalvehiclestates;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_AIRBAGDATA;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_TANKINFO;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DIMMEDHEADLIGHT;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_ACOUSTICPARKINGSYSTEM;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_CARVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_TVVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_HDDVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERSLIDESHOWVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERBORDBOOKVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERTRAVELAGENTVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERWEBVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BWSVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_RADIOTEXTVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DISPLAYDAYNIGHTDESIGN;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BTBONDINGVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_MESSAGINGVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DESTINATIONINPUTVELOCITYTHRESHOLD;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_REVERSEGEAR;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DSSSVIEWOPTION;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_VEHICLESTANDSTILL;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_SERVICEKEYDATA;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_SERVICEKEYVIEWOPTION;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_PERSONALIZATIONSTATUS;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_TLOVIEWOPTIONS;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_EMERGENCYASSISTVOLLOWERING;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_PARKINGBRAKE;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_APPCONNECTTRIGGER;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_STPSTATE;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_AUTOMATICGEARSHIFTTRANSMODE;
}

