/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.startup;

public class Consts {
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSROOT;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSTUNER;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMEDIA;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSADDRESSBOOK;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSPHONE;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSNAV;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSINFO;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSCAR;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSAUDIO;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSDS;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSWDL;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEARLYAPPS;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSPOSTSTARTUP;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSCOMMUNICATION;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSIPSERVICES;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSGEMMI;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSBAPKOMBI;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSBLUETOOTH;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSBROWSER;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEXPLORER;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSCALENDAR;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSPICTURESTORE;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSTREETVIEW;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMOBILITYHORIZON;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEXBOXM;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMIRRORLINK;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSFA;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSEARCH;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSDIAGNOSIS;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSASIALANGUAGESUPPORT;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEXLAP;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSTVTUNER;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMEDIAONLINE;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMEDIAROUTER;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSRADIODATASERVER;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSMARTPHONEINTEGRATION;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSWIRELESSCHARGER;
}

